# Ativa o servidor WebSocket
websocket_port = 30000
websocket_address = 0.0.0.0

# Configurações básicas do servidor
name = Servidor Brasil!!
description = Servidor Luanti rodando no Render via WebSockets!
creative_mode = false
enable_damage = true
